# Diccionario de traducciones
traducciones = {
    'es': {
        'auto_open': 'Abrir presentación automáticamente',
        'num_diapositivas': 'Número de diapositivas:',
        'descripcion_presentacion': 'Describa su presentación:',
        'imagen_modelo': 'Modelo de IA de Imagen:',
        'texto_modelo': 'Modelo de IA de Texto:',
        'description_text': 'Configura una clave API de Google, Replicate, o xAI para poder utilizar el programa',
        'contador_label': '{} palabras',
        'obtener_google_api': 'Obtener clave API de Google',
        'configurar_google_api': 'Configurar clave API de Google',
        'borrar_google_api': 'Borrar clave API de Google',
        'obtener_replicate_api': 'Obtener clave API de Replicate',
        'configurar_replicate_api': 'Configurar clave API de Replicate',
        'borrar_replicate_api': 'Borrar clave API de Replicate',
        'obtener_xai_api': 'Obtener clave API de xAI',
        'configurar_xai_api': 'Configurar clave API de xAI',
        'borrar_xai_api': 'Borrar clave API de xAI',
        'cargar_pdf': 'Cargar documento',
        'pdf_cargado': 'Documento cargado: {}',
        'eliminar_pdf': 'Eliminar',
        'error_cargar_pdf': 'Error al cargar el documento',
        'error_pdf_vacio': 'El documento no contiene texto que pueda ser extraído',
        'pdf_filter': 'Documentos (*.pdf *.txt)',
        'seleccionar_pdf': 'Seleccionar documento',
        'google_api_config_window': 'Configuración API Google',
        'google_api_key_prompt': 'Escriba su clave API de Google:',
        'copy_api_clipboard': 'Copiar API al portapapeles',
        'valid_key': 'Clave válida',
        'validate_save': 'Validar y guardar',
        'empty_field_error': 'No puede dejar el campo vacío',
        'invalid_key': 'Clave inválida',
        'timeout_error': 'Error de conexión: Timeout',
        'connection_error': 'Error de conexión: No se pudo conectar al servidor',
        'generic_error': 'Error de conexión: {}',
        'replicate_api_config_window': 'Configuración API Replicate',
        'replicate_api_key_prompt': 'Escriba su clave API de Replicate:',
        'xai_api_config_window': 'Configuración API xAI',
        'xai_api_key_prompt': 'Escriba su clave API de xAI:',
        'invalid_key_format': 'Formato de clave inválido. Debe comenzar con "xai-"',
        'balance_window_title': 'Saldo total',
        'text_costs': 'Texto: ${:.5f}',
        'image_costs': 'Imágenes: ${:.5f}',
        'total_costs': 'Total: ${:.5f}',
        'check_xai_balance': 'Revisar en xAI',
        'check_replicate_balance': 'Revisar en Replicate',
        'reset_costs': 'Reiniciar los costes',
        'confirm_reset_title': 'Confirmar reinicio',
        'confirm_reset_message': '¿Está seguro de que quiere reiniciar los costes a cero?',
        'yes': 'Sí',
        'no': 'No',
        'accumulated_costs_title': 'Costos totales aproximados acumulados',
        'google_delete_confirm_title': 'Confirmar borrado API Google',
        'google_delete_confirm_message': '¿Está seguro de que desea borrar la clave API de Google?',
        'google_invalid_api_title': 'API Google inválida',
        'google_invalid_api_message': 'La clave API de Google no es válida. Escribe una nueva clave API de Google.',
        'google_connection_error_title': 'Error de conexión con Google',
        'google_connection_error_message': 'No se pudo validar la clave API de Google. Verifica tu conexión a internet.',
        'google_api_deleted_title': 'Clave API borrada',
        'google_api_deleted_message': 'La clave API de Google ha sido borrada correctamente.',
        'replicate_delete_confirm_title': 'Confirmar borrado API Replicate',
        'replicate_delete_confirm_message': '¿Está seguro de que desea borrar la clave API de Replicate?',
        'replicate_api_deleted_title': 'Clave API borrada',
        'replicate_api_deleted_message': 'La clave API de Replicate ha sido borrada correctamente.',
        'xai_delete_confirm_title': 'Confirmar borrado API xAI',
        'xai_delete_confirm_message': '¿Está seguro de que desea borrar la clave API de xAI?',
        'xai_api_deleted_title': 'Clave API borrada',
        'xai_api_deleted_message': 'La clave API de xAI ha sido borrada correctamente.',
        'language_instruction': 'español',
        'connection_error_title': 'Error de conexión',
        'connection_error_message': 'No se detectó conexión a Internet.\nPowerpoineador necesita una conexión a Internet para funcionar.',
        'retry': 'Reintentar',
        'exit': 'Salir',
        'too_many_words': 'La descripción contiene demasiadas palabras. Por favor reduzca el texto.',
        'too_few_words': 'La descripción debe tener al menos 10 palabras.',
        'empty_description': 'Por favor, escriba una descripción para su presentación.',
        'image_required': 'Debe cargar una imagen para usar este modelo de imagen.',
        'save_presentation': 'Guardar presentación',
        'default_filename': 'Presentación_Powerpoineador.pptx',
        'pptx_filter': 'Presentaciones (*.pptx)',
        'vista_previa_title': 'Vista previa de diapositivas',
        'vista_previa_empty_message': 'Aquí se mostrarán las vistas previas\nde las diapositivas conforme\nse vayan generando.',
        'generating_window_title': 'Generando PowerPoint...',
        'app_title': 'Powerpoineador',
        'generation_successful': '¡Presentación generada exitosamente!',
        'presentation_ready': 'Presentación lista',
        'presentation_generated_successfully': 'Su presentación "{nombre_archivo}" ha sido generada correctamente en:\n{ruta_completa}',
        'generation_finish_error': 'Error al finalizar la generación: {error}',
        'generation_cancelled': 'Generación cancelada por el usuario.',
        'confirm_cancellation': 'Confirmar cancelación',
        'cancel_generation_confirm': '¿Está seguro de que desea cancelar la generación?',
        'error': 'Error',
        'generation_error': 'Error al generar la presentación: {error}',
        'intentando_generar_respuesta': 'Intentando generar respuesta con {modelo}...',
        'respuesta_modelo': 'Respuesta del modelo {modelo}: {respuesta}',
        'tupla_generada': 'La tupla generada por el modelo fue: {respuesta}',
        'error_obtener_respuesta': 'Error en obtener_respuesta_ia: {error}',
        'generando_texto': 'Generando texto con el modelo {modelo}...',
        'no_respuesta_modelo_texto': 'No se pudo obtener respuesta del modelo de texto',
        'generando_imagen': '\nGenerando imagen {numero}/{total}',
        'imagen_generada_correctamente': 'Imagen {numero} generada correctamente',
        'error_generando_imagen': 'Error generando imagen {numero}: {error}',
        'aplicando_disenos': '\nAplicando diseños a las diapositivas...',
        'diapositiva_completada': 'Diapositiva {numero}/{total} completada',
        'error_aplicando_diseno': 'Error aplicando diseño a diapositiva {numero}: {error}',
        'error_generacion_presentacion': 'Error durante la generación de la presentación: {error}',
        'error_generar_imagen': 'Error al generar imagen: {error}',
        'error_imagen_requerida': 'Se requiere una imagen personalizada válida para este modelo',
        'slide_previous': 'Anterior',
        'slide_next': 'Siguiente',
        'update_available_title': 'Actualización disponible',
        'update_available_message': 'Hay una nueva versión de Powerpoineador disponible.\n\nVersión actual: {version_actual}\nNueva versión: {version_nueva}\n\n¿Desea descargarla?',
        'intentando_generar_imagen': 'intentando_generar_imagen',
        'respuesta_completa_modelo': 'Respuesta completa del modelo: {respuesta}',
        'respuesta_procesada': 'Respuesta procesada: {respuesta}',
        'error_generacion_respuesta': 'Error en la generación de respuesta: {error}',
        'error_intento': 'Error en intento {intento}: {error}',
        'respuesta_generada_exitosamente': 'Respuesta generada exitosamente',
        'respuesta_no_valida': 'La respuesta no es un diccionario válido, reintentando...',
        'error_generacion_imagen': 'Error en la generación de imagen: {error}',
        'error_generacion_imagen_gemini': 'Error en la generación de imagen con Gemini: {error}',
        'texto_recibido_modelo': 'Texto recibido del modelo: {texto}',
        'imagen_no_generada': 'No se generó ninguna imagen en la respuesta',
        'confirm_exit': 'Confirmar salida',
        'generation_in_progress': 'Hay una generación en curso. ¿Está seguro de que desea salir?',
        'cancel_generation': 'CANCELAR',
        'ocultar_log': 'Ocultar progreso',
        'mostrar_log': 'Mostrar progreso',
        'revisar_pdf': 'Revisar',
        'error_abrir_pdf': 'Error al abrir el documento: {error}',
        'aviso': 'Aviso',
        'ningun_documento': 'No hay ningún documento cargado',
        'font_label': 'Fuente de letra:',
        'title_font_label': 'Fuente del título:',
        'content_font_label': 'Fuente del contenido:',
        'title_font_size_label': 'Tamaño del título:',
        'content_font_size_label': 'Tamaño del contenido:'
    },
    'en': {
        'auto_open': 'Automatically open presentation',
        'num_diapositivas': 'Number of slides:',
        'descripcion_presentacion': 'Describe your presentation:',
        'imagen_modelo': 'Image AI model:',
        'texto_modelo': 'Text AI model:',
        'description_text': 'Configure a Google, Replicate, or xAI API key to use the program',
        'contador_label': '{} words',
        'obtener_google_api': 'Get Google API key',
        'configurar_google_api': 'Configure Google API key',
        'borrar_google_api': 'Delete Google API key',
        'obtener_replicate_api': 'Get Replicate API key',
        'configurar_replicate_api': 'Configure Replicate API key',
        'borrar_replicate_api': 'Delete Replicate API key',
        'obtener_xai_api': 'Get xAI API key',
        'configurar_xai_api': 'Configure xAI API key',
        'borrar_xai_api': 'Delete xAI API key',
        'cargar_pdf': 'Load document',
        'pdf_cargado': 'Document loaded: {}',
        'eliminar_pdf': 'Remove',
        'error_cargar_pdf': 'Error loading document',
        'error_pdf_vacio': 'The document does not contain text that can be extracted',
        'pdf_filter': 'Documents (*.pdf *.txt)',
        'seleccionar_pdf': 'Select document',
        'google_api_config_window': 'Google API Configuration',
        'google_api_key_prompt': 'Enter your Google API key:',
        'copy_api_clipboard': 'Copy API to clipboard',
        'valid_key': 'Valid key',
        'validate_save': 'Validate and save',
        'empty_field_error': 'Field cannot be empty',
        'invalid_key': 'Invalid key',
        'timeout_error': 'Connection error: Timeout',
        'connection_error': 'Connection error: Could not connect to server',
        'generic_error': 'Connection error: {}',
        'replicate_api_config_window': 'Replicate API Configuration',
        'replicate_api_key_prompt': 'Enter your Replicate API key:',
        'xai_api_config_window': 'xAI API Configuration',
        'xai_api_key_prompt': 'Enter your xAI API key:',
        'invalid_key_format': 'Invalid key format. Must start with "xai-"',
        'balance_window_title': 'Total balance',
        'text_costs': 'Text: ${:.5f}',
        'image_costs': 'Images: ${:.5f}',
        'total_costs': 'Total: ${:.5f}',
        'check_xai_balance': 'Check on xAI',
        'check_replicate_balance': 'Check on Replicate',
        'reset_costs': 'Reset costs',
        'confirm_reset_title': 'Confirm reset',
        'confirm_reset_message': 'Are you sure you want to reset the costs to zero?',
        'yes': 'Yes',
        'no': 'No',
        'accumulated_costs_title': 'Total accumulated approximate costs',
        'google_delete_confirm_title': 'Confirm Google API deletion',
        'google_delete_confirm_message': 'Are you sure you want to delete the Google API key?',
        'google_invalid_api_title': 'Invalid Google API',
        'google_invalid_api_message': 'The Google API key is not valid. Enter a new Google API key.',
        'google_connection_error_title': 'Google connection error',
        'google_connection_error_message': 'Could not validate the Google API key. Check your internet connection.',
        'google_api_deleted_title': 'API key deleted',
        'google_api_deleted_message': 'The Google API key has been successfully deleted.',
        'replicate_delete_confirm_title': 'Confirm Replicate API deletion',
        'replicate_delete_confirm_message': 'Are you sure you want to delete the Replicate API key?',
        'replicate_api_deleted_title': 'API key deleted',
        'replicate_api_deleted_message': 'The Replicate API key has been successfully deleted.',
        'xai_delete_confirm_title': 'Confirm xAI API deletion',
        'xai_delete_confirm_message': 'Are you sure you want to delete the xAI API key?',
        'xai_api_deleted_title': 'API key deleted',
        'xai_api_deleted_message': 'The xAI API key has been successfully deleted.',
        'language_instruction': 'english',
        'connection_error_title': 'Connection Error',
        'connection_error_message': 'No Internet connection detected.\nPowerpoineator needs an Internet connection to function.',
        'retry': 'Retry',
        'exit': 'Exit',
        'too_many_words': 'The description contains too many words. Please reduce the text.',
        'too_few_words': 'The description must have at least 10 words.',
        'empty_description': 'Please write a description for your presentation.',
        'image_required': 'You must upload an image to use this image model.',
        'save_presentation': 'Save presentation',
        'default_filename': 'Powerpoineator_Presentation.pptx',
        'pptx_filter': 'Presentations (*.pptx)',
        'vista_previa_title': 'Slides preview',
        'vista_previa_empty_message': 'The previews of the slides\nwill be displayed here\nas they are generated.',
        'generating_window_title': 'Generating PowerPoint...',
        'app_title': 'Powerpoineator',
        'generation_successful': 'Presentation successfully generated!',
        'presentation_ready': 'Presentation ready',
        'presentation_generated_successfully': 'Your presentation "{nombre_archivo}" has been successfully generated at:\n{ruta_completa}',
        'generation_finish_error': 'Error finishing generation: {error}',
        'generation_cancelled': 'Generation cancelled by user.',
        'confirm_cancellation': 'Confirm cancellation',
        'cancel_generation_confirm': 'Are you sure you want to cancel the current generation?',
        'error': 'Error',
        'generation_error': 'Error generating presentation: {error}',
        'intentando_generar_respuesta': 'Trying to generate response with {modelo}...',
        'respuesta_modelo': 'Response from model {modelo}: {respuesta}',
        'tupla_generada': 'The tuple generated by the model was: {respuesta}',
        'error_obtener_respuesta': 'Error in obtener_respuesta_ia: {error}',
        'generando_texto': 'Generating text with model {modelo}...',
        'no_respuesta_modelo_texto': 'Could not get response from text model',
        'generando_imagen': '\nGenerating image {numero}/{total}',
        'imagen_generada_correctamente': 'Image {numero} generated successfully',
        'error_generando_imagen': 'Error generating image {numero}: {error}',
        'aplicando_disenos': '\nApplying designs to slides...',
        'diapositiva_completada': 'Slide {numero}/{total} completed',
        'error_aplicando_diseno': 'Error applying design to slide {numero}: {error}',
        'error_generacion_presentacion': 'Error during presentation generation: {error}',
        'error_generar_imagen': 'Error generating image: {error}',
        'error_imagen_requerida': 'A valid custom image is required for this model',
        'slide_previous': 'Previous',
        'slide_next': 'Next',
        'update_available_title': 'Update available',
        'update_available_message': 'A new version of Powerpoineator is available.\n\nCurrent version: {version_actual}\nNew version: {version_nueva}\n\nDo you want to download it?',
        'intentando_generar_imagen': 'trying_to_generate_image',
        'respuesta_completa_modelo': 'Complete model response: {respuesta}',
        'respuesta_procesada': 'Processed response: {respuesta}',
        'error_generacion_respuesta': 'Error in response generation: {error}',
        'error_intento': 'Error in attempt {intento}: {error}',
        'respuesta_generada_exitosamente': 'Response successfully generated',
        'respuesta_no_valida': 'The response is not a valid dictionary, retrying...',
        'error_generacion_imagen': 'Error in image generation: {error}',
        'error_generacion_imagen_gemini': 'Error in image generation with Gemini: {error}',
        'texto_recibido_modelo': 'Text received from model: {texto}',
        'imagen_no_generada': 'No image was generated in the response',
        'confirm_exit': 'Confirm exit',
        'generation_in_progress': 'There is a generation in progress. Are you sure you want to exit?',
        'cancel_generation': 'CANCEL',
        'ocultar_log': 'Hide progress',
        'mostrar_log': 'Show progress',
        'revisar_pdf': 'Review',
        'error_abrir_pdf': 'Error opening document: {error}',
        'aviso': 'Notice',
        'ningun_documento': 'No document loaded',
        'font_label': 'Letter font:',
        'title_font_label': 'Title font:',
        'content_font_label': 'Content font:',
        'title_font_size_label': 'Title size:',
        'content_font_size_label': 'Content size:'
    }
}

def obtener_traduccion(clave, idioma='es'):
    return traducciones.get(idioma, {}).get(clave, clave)