# Diccionario de traducciones
traducciones = {
    'es': {
        'auto_open': 'Abrir presentación automáticamente',
        'num_diapositivas': 'Número de diapositivas:',
        'descripcion_presentacion': 'Describa su presentación:',
        'imagen_modelo': 'Modelo de IA de Imagen:',
        'texto_modelo': 'Modelo de IA de Texto:',
        'description_text': 'Configura una clave API de Google, Replicate, o xAI para poder utilizar el programa',
        'contador_label': '{} palabras',
        'obtener_google_api': 'Obtener clave API de Google',
        'configurar_google_api': 'Configurar clave API de Google',
        'borrar_google_api': 'Borrar clave API de Google',
        'obtener_replicate_api': 'Obtener clave API de Replicate',
        'configurar_replicate_api': 'Configurar clave API de Replicate',
        'borrar_replicate_api': 'Borrar clave API de Replicate',
        'obtener_xai_api': 'Obtener clave API de xAI',
        'configurar_xai_api': 'Configurar clave API de xAI',
        'borrar_xai_api': 'Borrar clave API de xAI',
        'cargar_pdf': 'Cargar documento',
        'pdf_cargado': 'Documento cargado: {}',
        'eliminar_pdf': 'Eliminar',
        'error_cargar_pdf': 'Error al cargar el documento',
        'error_pdf_vacio': 'El documento no contiene texto que pueda ser extraído',
        'pdf_filter': 'Documentos (*.pdf *.txt)',
        'seleccionar_pdf': 'Seleccionar documento',
        'google_api_config_window': 'Configuración API Google',
        'google_api_key_prompt': 'Escriba su clave API de Google:',
        'copy_api_clipboard': 'Copiar API al portapapeles',
        'valid_key': 'Clave válida',
        'validate_save': 'Validar y guardar',
        'empty_field_error': 'No puede dejar el campo vacío',
        'invalid_key': 'Clave inválida',
        'timeout_error': 'Error de conexión: Timeout',
        'connection_error': 'Error de conexión: No se pudo conectar al servidor',
        'generic_error': 'Error de conexión: {}',
        'replicate_api_config_window': 'Configuración API Replicate',
        'replicate_api_key_prompt': 'Escriba su clave API de Replicate:',
        'xai_api_config_window': 'Configuración API xAI',
        'xai_api_key_prompt': 'Escriba su clave API de xAI:',
        'invalid_key_format': 'Formato de clave inválido. Debe comenzar con "xai-"',
        'balance_window_title': 'Saldo total',
        'text_costs': 'Texto: ${:.5f}',
        'image_costs': 'Imágenes: ${:.5f}',
        'total_costs': 'Total: ${:.5f}',
        'check_xai_balance': 'Revisar en xAI',
        'check_replicate_balance': 'Revisar en Replicate',
        'reset_costs': 'Reiniciar los costes',
        'confirm_reset_title': 'Confirmar reinicio',
        'confirm_reset_message': '¿Está seguro de que quiere reiniciar los costes a cero?',
        'yes': 'Sí',
        'no': 'No',
        'accumulated_costs_title': 'Costos totales aproximados acumulados',
        'google_delete_confirm_title': 'Confirmar borrado API Google',
        'google_delete_confirm_message': '¿Está seguro de que desea borrar la clave API de Google?',
        'google_invalid_api_title': 'API Google inválida',
        'google_invalid_api_message': 'La clave API de Google no es válida. Escribe una nueva clave API de Google.',
        'google_connection_error_title': 'Error de conexión con Google',
        'google_connection_error_message': 'No se pudo validar la clave API de Google. Verifica tu conexión a internet.',
        'google_api_deleted_title': 'Clave API borrada',
        'google_api_deleted_message': 'La clave API de Google ha sido borrada correctamente.',
        'replicate_delete_confirm_title': 'Confirmar borrado API Replicate',
        'replicate_delete_confirm_message': '¿Está seguro de que desea borrar la clave API de Replicate?',
        'replicate_api_deleted_title': 'Clave API borrada',
        'replicate_api_deleted_message': 'La clave API de Replicate ha sido borrada correctamente.',
        'xai_delete_confirm_title': 'Confirmar borrado API xAI',
        'xai_delete_confirm_message': '¿Está seguro de que desea borrar la clave API de xAI?',
        'xai_api_deleted_title': 'Clave API borrada',
        'xai_api_deleted_message': 'La clave API de xAI ha sido borrada correctamente.',
        'language_instruction': 'español',
        'connection_error_title': 'Error de conexión',
        'connection_error_message': 'No se detectó conexión a Internet.\nPowerpoineador necesita una conexión a Internet para funcionar.',
        'retry': 'Reintentar',
        'exit': 'Salir',
        'too_many_words': 'La descripción contiene demasiadas palabras. Por favor reduzca el texto.',
        'too_few_words': 'La descripción debe tener al menos 10 palabras.',
        'empty_description': 'Por favor, escriba una descripción para su presentación.',
        'image_required': 'Debe cargar una imagen para usar este modelo de imagen.',
        'save_presentation': 'Guardar presentación',
        'default_filename': 'Presentación_Powerpoineador.pptx',
        'pptx_filter': 'Presentaciones (*.pptx)',
        'vista_previa_title': 'Vista previa de diapositivas',
        'vista_previa_empty_message': 'Aquí se mostrarán las vistas previas\nde las diapositivas conforme\nse vayan generando.',
        'generating_window_title': 'Generando PowerPoint...',
        'app_title': 'Powerpoineador',
        'generation_successful': '¡Presentación generada exitosamente!',
        'presentation_ready': 'Presentación lista',
        'presentation_generated_successfully': 'Su presentación "{nombre_archivo}" ha sido generada correctamente en:\n{ruta_completa}',
        'generation_finish_error': 'Error al finalizar la generación: {error}',
        'generation_cancelled': 'Generación cancelada por el usuario.',
        'confirm_cancellation': 'Confirmar cancelación',
        'cancel_generation_confirm': '¿Está seguro de que desea cancelar la generación?',
        'error': 'Error',
        'generation_error': 'Error al generar la presentación: {error}',
        'intentando_generar_respuesta': 'Intentando generar respuesta con {modelo}...',
        'respuesta_modelo': 'Respuesta del modelo {modelo}: {respuesta}',
        'tupla_generada': 'La tupla generada por el modelo fue: {respuesta}',
        'error_obtener_respuesta': 'Error en obtener_respuesta_ia: {error}',
        'generando_texto': 'Generando texto con el modelo {modelo}...',
        'no_respuesta_modelo_texto': 'No se pudo obtener respuesta del modelo de texto',
        'generando_imagen': '\nGenerando imagen {numero}/{total}',
        'imagen_generada_correctamente': 'Imagen {numero} generada correctamente',
        'error_generando_imagen': 'Error generando imagen {numero}: {error}',
        'aplicando_disenos': '\nAplicando diseños a las diapositivas...',
        'diapositiva_completada': 'Diapositiva {numero}/{total} completada',
        'error_aplicando_diseno': 'Error aplicando diseño a diapositiva {numero}: {error}',
        'error_generacion_presentacion': 'Error durante la generación de la presentación: {error}',
        'error_generar_imagen': 'Error al generar imagen: {error}',
        'error_imagen_requerida': 'Se requiere una imagen personalizada válida para este modelo',
        'slide_previous': 'Anterior',
        'slide_next': 'Siguiente',
        'update_available_title': 'Actualización disponible',
        'update_available_message': 'Hay una nueva versión de Powerpoineador disponible.\n\nVersión actual: {version_actual}\nNueva versión: {version_nueva}\n\n¿Desea descargarla?',
        'intentando_generar_imagen': 'Reintentando generar imagen',
        'respuesta_completa_modelo': 'Respuesta completa del modelo: {respuesta}',
        'respuesta_procesada': 'Respuesta procesada: {respuesta}',
        'error_generacion_respuesta': 'Error en la generación de respuesta: {error}',
        'error_intento': 'Error en intento {intento}: {error}',
        'respuesta_generada_exitosamente': 'Respuesta generada exitosamente',
        'respuesta_no_valida': 'La respuesta no es un diccionario válido, reintentando...',
        'error_generacion_imagen': 'Error en la generación de imagen: {error}',
        'error_generacion_imagen_gemini': 'Error en la generación de imagen con Gemini: {error}',
        'texto_recibido_modelo': 'Texto recibido del modelo: {texto}',
        'imagen_no_generada': 'No se generó ninguna imagen en la respuesta',
        'confirm_exit': 'Confirmar salida',
        'generation_in_progress': 'Hay una generación en curso. ¿Está seguro de que desea salir?',
        'cancel_generation': 'CANCELAR',
        'ocultar_log': 'Ocultar progreso',
        'mostrar_log': 'Mostrar progreso',
        'revisar_pdf': 'Revisar',
        'error_abrir_pdf': 'Error al abrir el documento: {error}',
        'aviso': 'Aviso',
        'ningun_documento': 'No hay ningún documento cargado',
        'font_label': 'Fuente de letra:',
        'title_font_label': 'Fuente del título:',
        'content_font_label': 'Fuente del contenido:',
        'title_font_size_label': 'Tamaño del título:',
        'content_font_size_label': 'Tamaño del contenido:',
        'title_bold': 'Negrita',
        'title_italic': 'Cursiva',
        'title_underline': 'Subrayado',
        'content_bold': 'Negrita',
        'content_italic': 'Cursiva',
        'content_underline': 'Subrayado',
        'language_option_es': 'Español',
        'language_option_en': 'Inglés',
        'language_option_fr': 'Francés',
        'language_option_pt': 'Portugués',
        'language_option_it': 'Italiano',
        'language_option_de': 'Alemán'
    },
    'en': {
        'auto_open': 'Automatically open presentation',
        'num_diapositivas': 'Number of slides:',
        'descripcion_presentacion': 'Describe your presentation:',
        'imagen_modelo': 'Image AI model:',
        'texto_modelo': 'Text AI model:',
        'description_text': 'Configure a Google, Replicate, or xAI API key to use the program',
        'contador_label': '{} words',
        'obtener_google_api': 'Get Google API key',
        'configurar_google_api': 'Configure Google API key',
        'borrar_google_api': 'Delete Google API key',
        'obtener_replicate_api': 'Get Replicate API key',
        'configurar_replicate_api': 'Configure Replicate API key',
        'borrar_replicate_api': 'Delete Replicate API key',
        'obtener_xai_api': 'Get xAI API key',
        'configurar_xai_api': 'Configure xAI API key',
        'borrar_xai_api': 'Delete xAI API key',
        'cargar_pdf': 'Load document',
        'pdf_cargado': 'Document loaded: {}',
        'eliminar_pdf': 'Remove',
        'error_cargar_pdf': 'Error loading document',
        'error_pdf_vacio': 'The document does not contain text that can be extracted',
        'pdf_filter': 'Documents (*.pdf *.txt)',
        'seleccionar_pdf': 'Select document',
        'google_api_config_window': 'Google API Configuration',
        'google_api_key_prompt': 'Enter your Google API key:',
        'copy_api_clipboard': 'Copy API to clipboard',
        'valid_key': 'Valid key',
        'validate_save': 'Validate and save',
        'empty_field_error': 'Field cannot be empty',
        'invalid_key': 'Invalid key',
        'timeout_error': 'Connection error: Timeout',
        'connection_error': 'Connection error: Could not connect to server',
        'generic_error': 'Connection error: {}',
        'replicate_api_config_window': 'Replicate API Configuration',
        'replicate_api_key_prompt': 'Enter your Replicate API key:',
        'xai_api_config_window': 'xAI API Configuration',
        'xai_api_key_prompt': 'Enter your xAI API key:',
        'invalid_key_format': 'Invalid key format. Must start with "xai-"',
        'balance_window_title': 'Total balance',
        'text_costs': 'Text: ${:.5f}',
        'image_costs': 'Images: ${:.5f}',
        'total_costs': 'Total: ${:.5f}',
        'check_xai_balance': 'Check on xAI',
        'check_replicate_balance': 'Check on Replicate',
        'reset_costs': 'Reset costs',
        'confirm_reset_title': 'Confirm reset',
        'confirm_reset_message': 'Are you sure you want to reset the costs to zero?',
        'yes': 'Yes',
        'no': 'No',
        'accumulated_costs_title': 'Total accumulated approximate costs',
        'google_delete_confirm_title': 'Confirm Google API deletion',
        'google_delete_confirm_message': 'Are you sure you want to delete the Google API key?',
        'google_invalid_api_title': 'Invalid Google API',
        'google_invalid_api_message': 'The Google API key is not valid. Enter a new Google API key.',
        'google_connection_error_title': 'Google connection error',
        'google_connection_error_message': 'Could not validate the Google API key. Check your internet connection.',
        'google_api_deleted_title': 'API key deleted',
        'google_api_deleted_message': 'The Google API key has been successfully deleted.',
        'replicate_delete_confirm_title': 'Confirm Replicate API deletion',
        'replicate_delete_confirm_message': 'Are you sure you want to delete the Replicate API key?',
        'replicate_api_deleted_title': 'API key deleted',
        'replicate_api_deleted_message': 'The Replicate API key has been successfully deleted.',
        'xai_delete_confirm_title': 'Confirm xAI API deletion',
        'xai_delete_confirm_message': 'Are you sure you want to delete the xAI API key?',
        'xai_api_deleted_title': 'API key deleted',
        'xai_api_deleted_message': 'The xAI API key has been successfully deleted.',
        'language_instruction': 'english',
        'connection_error_title': 'Connection Error',
        'connection_error_message': 'No Internet connection detected.\nPowerpoineator needs an Internet connection to function.',
        'retry': 'Retry',
        'exit': 'Exit',
        'too_many_words': 'The description contains too many words. Please reduce the text.',
        'too_few_words': 'The description must have at least 10 words.',
        'empty_description': 'Please write a description for your presentation.',
        'image_required': 'You must upload an image to use this image model.',
        'save_presentation': 'Save presentation',
        'default_filename': 'Powerpoineator_Presentation.pptx',
        'pptx_filter': 'Presentations (*.pptx)',
        'vista_previa_title': 'Slides preview',
        'vista_previa_empty_message': 'The previews of the slides\nwill be displayed here\nas they are generated.',
        'generating_window_title': 'Generating PowerPoint...',
        'app_title': 'Powerpoineator',
        'generation_successful': 'Presentation successfully generated!',
        'presentation_ready': 'Presentation ready',
        'presentation_generated_successfully': 'Your presentation "{nombre_archivo}" has been successfully generated at:\n{ruta_completa}',
        'generation_finish_error': 'Error finishing generation: {error}',
        'generation_cancelled': 'Generation cancelled by user.',
        'confirm_cancellation': 'Confirm cancellation',
        'cancel_generation_confirm': 'Are you sure you want to cancel the current generation?',
        'error': 'Error',
        'generation_error': 'Error generating presentation: {error}',
        'intentando_generar_respuesta': 'Trying to generate response with {modelo}...',
        'respuesta_modelo': 'Response from model {modelo}: {respuesta}',
        'tupla_generada': 'The tuple generated by the model was: {respuesta}',
        'error_obtener_respuesta': 'Error in obtener_respuesta_ia: {error}',
        'generando_texto': 'Generating text with model {modelo}...',
        'no_respuesta_modelo_texto': 'Could not get response from text model',
        'generando_imagen': '\nGenerating image {numero}/{total}',
        'imagen_generada_correctamente': 'Image {numero} generated successfully',
        'error_generando_imagen': 'Error generating image {numero}: {error}',
        'aplicando_disenos': '\nApplying designs to slides...',
        'diapositiva_completada': 'Slide {numero}/{total} completed',
        'error_aplicando_diseno': 'Error applying design to slide {numero}: {error}',
        'error_generacion_presentacion': 'Error during presentation generation: {error}',
        'error_generar_imagen': 'Error generating image: {error}',
        'error_imagen_requerida': 'A valid custom image is required for this model',
        'slide_previous': 'Previous',
        'slide_next': 'Next',
        'update_available_title': 'Update available',
        'update_available_message': 'A new version of Powerpoineator is available.\n\nCurrent version: {version_actual}\nNew version: {version_nueva}\n\nDo you want to download it?',
        'intentando_generar_imagen': 'Retrying image generation',
        'respuesta_completa_modelo': 'Complete model response: {respuesta}',
        'respuesta_procesada': 'Processed response: {respuesta}',
        'error_generacion_respuesta': 'Error in response generation: {error}',
        'error_intento': 'Error in attempt {intento}: {error}',
        'respuesta_generada_exitosamente': 'Response successfully generated',
        'respuesta_no_valida': 'The response is not a valid dictionary, retrying...',
        'error_generacion_imagen': 'Error in image generation: {error}',
        'error_generacion_imagen_gemini': 'Error in image generation with Gemini: {error}',
        'texto_recibido_modelo': 'Text received from model: {texto}',
        'imagen_no_generada': 'No image was generated in the response',
        'confirm_exit': 'Confirm exit',
        'generation_in_progress': 'There is a generation in progress. Are you sure you want to exit?',
        'cancel_generation': 'CANCEL',
        'ocultar_log': 'Hide progress',
        'mostrar_log': 'Show progress',
        'revisar_pdf': 'Review',
        'error_abrir_pdf': 'Error opening document: {error}',
        'aviso': 'Notice',
        'ningun_documento': 'No document loaded',
        'font_label': 'Letter font:',
        'title_font_label': 'Title font:',
        'content_font_label': 'Content font:',
        'title_font_size_label': 'Title size:',
        'content_font_size_label': 'Content size:',
        'title_bold': 'Bold',
        'title_italic': 'Italic',
        'title_underline': 'Underline',
        'content_bold': 'Bold',
        'content_italic': 'Italic',
        'content_underline': 'Underline',
        'language_option_es': 'Spanish',
        'language_option_en': 'English',
        'language_option_fr': 'French',
        'language_option_pt': 'Portuguese',
        'language_option_it': 'Italian',
        'language_option_de': 'German'
    },
    'fr': {
        'auto_open': 'Ouvrir la présentation automatiquement',
        'num_diapositivas': 'Nombre de diapositives:',
        'descripcion_presentacion': 'Décrivez votre présentation:',
        'imagen_modelo': 'Modèle IA d\'image:',
        'texto_modelo': 'Modèle IA de texte:',
        'description_text': 'Configurez une clé API Google, Replicate ou xAI pour utiliser le programme',
        'contador_label': '{} mots',
        'obtener_google_api': 'Obtenir la clé API Google',
        'configurar_google_api': 'Configurer la clé API Google',
        'borrar_google_api': 'Supprimer la clé API Google',
        'obtener_replicate_api': 'Obtenir la clé API Replicate',
        'configurar_replicate_api': 'Configurer la clé API Replicate',
        'borrar_replicate_api': 'Supprimer la clé API Replicate',
        'obtener_xai_api': 'Obtenir la clé API xAI',
        'configurar_xai_api': 'Configurer la clé API xAI',
        'borrar_xai_api': 'Supprimer la clé API xAI',
        'cargar_pdf': 'Charger le document',
        'pdf_cargado': 'Document chargé: {}',
        'eliminar_pdf': 'Supprimer',
        'error_cargar_pdf': 'Erreur lors du chargement du document',
        'error_pdf_vacio': 'Le document ne contient aucun texte extractible',
        'pdf_filter': 'Documents (*.pdf *.txt)',
        'seleccionar_pdf': 'Sélectionner le document',
        'google_api_config_window': 'Configuration API Google',
        'google_api_key_prompt': 'Entrez votre clé API Google :',
        'copy_api_clipboard': 'Copier l\'API dans le presse-papiers',
        'valid_key': 'Clé valide',
        'validate_save': 'Valider et enregistrer',
        'empty_field_error': 'Le champ ne peut pas être vide',
        'invalid_key': 'Clé invalide',
        'timeout_error': 'Erreur de connexion : Timeout',
        'connection_error': 'Erreur de connexion : Impossible de se connecter au serveur',
        'generic_error': 'Erreur de connexion: {}',
        'replicate_api_config_window': 'Configuration API Replicate',
        'replicate_api_key_prompt': 'Entrez votre clé API Replicate :',
        'xai_api_config_window': 'Configuration API xAI',
        'xai_api_key_prompt': 'Entrez votre clé API xAI :',
        'invalid_key_format': 'Format de clé invalide. Doit commencer par "xai-"',
        'balance_window_title': 'Solde total',
        'text_costs': 'Texte : ${:.5f}',
        'image_costs': 'Images : ${:.5f}',
        'total_costs': 'Total : ${:.5f}',
        'check_xai_balance': 'Vérifier sur xAI',
        'check_replicate_balance': 'Vérifier sur Replicate',
        'reset_costs': 'Réinitialiser les coûts',
        'confirm_reset_title': 'Confirmer la réinitialisation',
        'confirm_reset_message': 'Êtes-vous sûr de vouloir remettre les coûts à zéro?',
        'yes': 'Oui',
        'no': 'Non',
        'accumulated_costs_title': 'Coûts totaux approximatifs accumulés',
        'google_delete_confirm_title': 'Confirmer la suppression de l\'API Google',
        'google_delete_confirm_message': 'Êtes-vous sûr de vouloir supprimer la clé API Google?',
        'google_invalid_api_title': 'API Google invalide',
        'google_invalid_api_message': 'La clé API Google n\'est pas valide. Entrez une nouvelle clé API Google.',
        'google_connection_error_title': 'Erreur de connexion Google',
        'google_connection_error_message': 'Impossible de valider la clé API Google. Vérifiez votre connexion Internet.',
        'google_api_deleted_title': 'Clé API supprimée',
        'google_api_deleted_message': 'La clé API Google a été supprimée avec succès.',
        'replicate_delete_confirm_title': 'Confirmer la suppression de l\'API Replicate',
        'replicate_delete_confirm_message': 'Êtes-vous sûr de vouloir supprimer la clé API Replicate?',
        'replicate_api_deleted_title': 'Clé API supprimée',
        'replicate_api_deleted_message': 'La clé API Replicate a été supprimée avec succès.',
        'xai_delete_confirm_title': 'Confirmer la suppression de l\'API xAI',
        'xai_delete_confirm_message': 'Êtes-vous sûr de vouloir supprimer la clé API xAI?',
        'xai_api_deleted_title': 'Clé API supprimée',
        'xai_api_deleted_message': 'La clé API xAI a été supprimée avec succès.',
        'language_instruction': 'français',
        'connection_error_title': 'Erreur de connexion',
        'connection_error_message': 'Aucune connexion Internet détectée.\nPowerpointeur nécessite une connexion Internet pour fonctionner.',
        'retry': 'Réessayer',
        'exit': 'Quitter',
        'too_many_words': 'La description contient trop de mots. Veuillez réduire le texte.',
        'too_few_words': 'La description doit comporter au moins 10 mots.',
        'empty_description': 'Veuillez écrire une description pour votre présentation.',
        'image_required': 'Vous devez charger une image pour utiliser ce modèle d\'image.',
        'save_presentation': 'Enregistrer la présentation',
        'default_filename': 'Presentation_Powerpointeur.pptx',
        'pptx_filter': 'Présentations (*.pptx)',
        'vista_previa_title': 'Aperçu des diapositives',
        'vista_previa_empty_message': 'Les aperçus des diapositives\nseront affichés ici\nà mesure qu\'ils seront générés.',
        'generating_window_title': 'Génération du PowerPoint...',
        'app_title': 'Powerpointeur',
        'generation_successful': 'Présentation générée avec succès!',
        'presentation_ready': 'Présentation prête',
        'presentation_generated_successfully': 'Votre présentation "{nombre_archivo}" a été générée correctement dans :\n{ruta_completa}',
        'generation_finish_error': 'Erreur lors de la finalisation de la génération: {error}',
        'generation_cancelled': 'Génération annulée par l\'utilisateur.',
        'confirm_cancellation': 'Confirmer l\'annulation',
        'cancel_generation_confirm': 'Êtes-vous sûr de vouloir annuler la génération en cours?',
        'error': 'Erreur',
        'generation_error': 'Erreur lors de la génération de la présentation: {error}',
        'intentando_generar_respuesta': 'Tentative de génération de réponse avec {modelo}...',
        'respuesta_modelo': 'Réponse du modèle {modelo}: {respuesta}',
        'tupla_generada': 'Le tuple généré par le modèle était : {respuesta}',
        'error_obtener_respuesta': 'Erreur dans obtener_respuesta_ia: {error}',
        'generando_texto': 'Génération de texte avec le modèle {modelo}...',
        'no_respuesta_modelo_texto': 'Impossible d\'obtenir une réponse du modèle de texte',
        'generando_imagen': '\nGénération de l\'image {numero}/{total}',
        'imagen_generada_correctamente': 'Image {numero} générée correctement',
        'error_generando_imagen': 'Erreur lors de la génération de l\'image {numero}: {error}',
        'aplicando_disenos': '\nApplication des mises en page aux diapositives...',
        'diapositiva_completada': 'Diapositive {numero}/{total} terminée',
        'error_aplicando_diseno': 'Erreur lors de l\'application de la mise en page à la diapositive {numero}: {error}',
        'error_generacion_presentacion': 'Erreur lors de la génération de la présentation: {error}',
        'error_generar_imagen': 'Erreur lors de la génération de l\'image: {error}',
        'error_imagen_requerida': 'Une image personnalisée valide est requise pour ce modèle',
        'slide_previous': 'Précédente',
        'slide_next': 'Suivante',
        'update_available_title': 'Mise à jour disponible',
        'update_available_message': 'Une nouvelle version de Powerpointeur est disponible.\n\nVersion actuelle: {version_actual}\nNouvelle version: {version_nueva}\n\nVoulez-vous la télécharger?',
        'intentando_generar_imagen': 'Nouvelle tentative de génération de l\'image',
        'respuesta_completa_modelo': 'Réponse complète du modèle: {respuesta}',
        'respuesta_procesada': 'Réponse traitée: {respuesta}',
        'error_generacion_respuesta': 'Erreur lors de la génération de la réponse: {error}',
        'error_intento': 'Erreur lors de la tentative {intento}: {error}',
        'respuesta_generada_exitosamente': 'Réponse générée avec succès',
        'respuesta_no_valida': 'La réponse n\'est pas un dictionnaire valide, nouvelle tentative...',
        'error_generacion_imagen': 'Erreur lors de la génération de l\'image: {error}',
        'error_generacion_imagen_gemini': 'Erreur lors de la génération de l\'image avec Gemini: {error}',
        'texto_recibido_modelo': 'Texte reçu du modèle: {texto}',
        'imagen_no_generada': 'Aucune image n\'a été générée dans la réponse',
        'confirm_exit': 'Confirmer la sortie',
        'generation_in_progress': 'Une génération est en cours. Êtes-vous sûr de vouloir quitter?',
        'cancel_generation': 'ANNULER',
        'ocultar_log': 'Masquer la progression',
        'mostrar_log': 'Afficher la progression',
        'revisar_pdf': 'Réviser',
        'error_abrir_pdf': 'Erreur lors de l\'ouverture du document: {error}',
        'aviso': 'Avertissement',
        'ningun_documento': 'Aucun document chargé',
        'font_label': 'Police de caractères:',
        'title_font_label': 'Police du titre:',
        'content_font_label': 'Police du contenu:',
        'title_font_size_label': 'Taille du titre:',
        'content_font_size_label': 'Taille du contenu:',
        'title_bold': 'Gras',
        'title_italic': 'Italique',
        'title_underline': 'Souligné',
        'content_bold': 'Gras',
        'content_italic': 'Italique',
        'content_underline': 'Souligné',
        'language_option_es': 'Espagnol',
        'language_option_en': 'Anglais',
        'language_option_fr': 'Français',
        'language_option_pt': 'Portugais',
        'language_option_it': 'Italien',
        'language_option_de': 'Allemand'
    },
    'pt': {
        'auto_open': 'Abrir apresentação automaticamente',
        'num_diapositivas': 'Número de slides:',
        'descripcion_presentacion': 'Descreva sua apresentação:',
        'imagen_modelo': 'Modelo de IA de Imagem:',
        'texto_modelo': 'Modelo de IA de Texto:',
        'description_text': 'Configure uma chave API do Google, Replicate ou xAI para usar o programa',
        'contador_label': '{} palavras',
        'obtener_google_api': 'Obter chave API do Google',
        'configurar_google_api': 'Configurar chave API do Google',
        'borrar_google_api': 'Excluir chave API do Google',
        'obtener_replicate_api': 'Obter chave API da Replicate',
        'configurar_replicate_api': 'Configurar chave API da Replicate',
        'borrar_replicate_api': 'Excluir chave API da Replicate',
        'obtener_xai_api': 'Obter chave API da xAI',
        'configurar_xai_api': 'Configurar chave API da xAI',
        'borrar_xai_api': 'Excluir chave API da xAI',
        'cargar_pdf': 'Carregar documento',
        'pdf_cargado': 'Documento carregado: {}',
        'eliminar_pdf': 'Remover',
        'error_cargar_pdf': 'Erro ao carregar o documento',
        'error_pdf_vacio': 'O documento não contém texto que possa ser extraído',
        'pdf_filter': 'Documentos (*.pdf *.txt)',
        'seleccionar_pdf': 'Selecionar documento',
        'google_api_config_window': 'Configuração API Google',
        'google_api_key_prompt': 'Digite sua chave API do Google:',
        'copy_api_clipboard': 'Copiar API para a área de transferência',
        'valid_key': 'Chave válida',
        'validate_save': 'Validar e salvar',
        'empty_field_error': 'O campo não pode ficar vazio',
        'invalid_key': 'Chave inválida',
        'timeout_error': 'Erro de conexão: Timeout',
        'connection_error': 'Erro de conexão: Não foi possível conectar ao servidor',
        'generic_error': 'Erro de conexão: {}',
        'replicate_api_config_window': 'Configuração API Replicate',
        'replicate_api_key_prompt': 'Digite sua chave API da Replicate:',
        'xai_api_config_window': 'Configuração API xAI',
        'xai_api_key_prompt': 'Digite sua chave API da xAI:',
        'invalid_key_format': 'Formato de chave inválido. Deve começar com "xai-"',
        'balance_window_title': 'Saldo total',
        'text_costs': 'Texto: ${:.5f}',
        'image_costs': 'Imagens: ${:.5f}',
        'total_costs': 'Total: ${:.5f}',
        'check_xai_balance': 'Verificar na xAI',
        'check_replicate_balance': 'Verificar na Replicate',
        'reset_costs': 'Redefinir custos',
        'confirm_reset_title': 'Confirmar redefinição',
        'confirm_reset_message': 'Tem certeza de que deseja redefinir os custos para zero?',
        'yes': 'Sim',
        'no': 'Não',
        'accumulated_costs_title': 'Custos totais aproximados acumulados',
        'google_delete_confirm_title': 'Confirmar exclusão da API Google',
        'google_delete_confirm_message': 'Tem certeza de que deseja excluir a chave API do Google?',
        'google_invalid_api_title': 'API Google inválida',
        'google_invalid_api_message': 'A chave API do Google não é válida. Digite uma nova chave API do Google.',
        'google_connection_error_title': 'Erro de conexão com Google',
        'google_connection_error_message': 'Não foi possível validar a chave API do Google. Verifique sua conexão com a internet.',
        'google_api_deleted_title': 'Chave API excluída',
        'google_api_deleted_message': 'A chave API do Google foi excluída com sucesso.',
        'replicate_delete_confirm_title': 'Confirmar exclusão da API Replicate',
        'replicate_delete_confirm_message': 'Tem certeza de que deseja excluir a chave API da Replicate?',
        'replicate_api_deleted_title': 'Chave API excluída',
        'replicate_api_deleted_message': 'A chave API da Replicate foi excluída com sucesso.',
        'xai_delete_confirm_title': 'Confirmar exclusão da API xAI',
        'xai_delete_confirm_message': 'Tem certeza de que deseja excluir a chave API da xAI?',
        'xai_api_deleted_title': 'Chave API excluída',
        'xai_api_deleted_message': 'A chave API da xAI foi excluída com sucesso.',
        'language_instruction': 'português',
        'connection_error_title': 'Erro de conexão',
        'connection_error_message': 'Nenhuma conexão com a Internet detectada.\nPowerpointador precisa de uma conexão com a Internet para funcionar.',
        'retry': 'Tentar novamente',
        'exit': 'Sair',
        'too_many_words': 'A descrição contém muitas palavras. Por favor, reduza o texto.',
        'too_few_words': 'A descrição deve ter pelo menos 10 palavras.',
        'empty_description': 'Por favor, escreva uma descrição para sua apresentação.',
        'image_required': 'Você deve carregar uma imagem para usar este modelo de imagem.',
        'save_presentation': 'Salvar apresentação',
        'default_filename': 'Apresentacao_Powerpointador.pptx',
        'pptx_filter': 'Apresentações (*.pptx)',
        'vista_previa_title': 'Visualização de slides',
        'vista_previa_empty_message': 'As visualizações dos slides\nserão exibidas aqui\nconforme forem geradas.',
        'generating_window_title': 'Gerando PowerPoint...',
        'app_title': 'Powerpointador',
        'generation_successful': 'Apresentação gerada com sucesso!',
        'presentation_ready': 'Apresentação pronta',
        'presentation_generated_successfully': 'Sua apresentação "{nombre_archivo}" foi gerada corretamente em:\n{ruta_completa}',
        'generation_finish_error': 'Erro ao finalizar a geração: {error}',
        'generation_cancelled': 'Geração cancelada pelo usuário.',
        'confirm_cancellation': 'Confirmar cancelamento',
        'cancel_generation_confirm': 'Tem certeza de que deseja cancelar a geração atual?',
        'error': 'Erro',
        'generation_error': 'Erro ao gerar a apresentação: {error}',
        'intentando_generar_respuesta': 'Tentando gerar resposta com {modelo}...',
        'respuesta_modelo': 'Resposta do modelo {modelo}: {respuesta}',
        'tupla_generada': 'A tupla gerada pelo modelo foi: {respuesta}',
        'error_obtener_respuesta': 'Erro em obtener_respuesta_ia: {error}',
        'generando_texto': 'Gerando texto com o modelo {modelo}...',
        'no_respuesta_modelo_texto': 'Não foi possível obter resposta do modelo de texto',
        'generando_imagen': '\nGerando imagem {numero}/{total}',
        'imagen_generada_correctamente': 'Imagem {numero} gerada corretamente',
        'error_generando_imagen': 'Erro ao gerar imagem {numero}: {error}',
        'aplicando_disenos': '\nAplicando designs aos slides...',
        'diapositiva_completada': 'Slide {numero}/{total} concluído',
        'error_aplicando_diseno': 'Erro ao aplicar design ao slide {numero}: {error}',
        'error_generacion_presentacion': 'Erro durante a geração da apresentação: {error}',
        'error_generar_imagen': 'Erro ao gerar imagem: {error}',
        'error_imagen_requerida': 'É necessária uma imagem personalizzada válida para este modelo',
        'slide_previous': 'Anterior',
        'slide_next': 'Próximo',
        'update_available_title': 'Atualização disponível',
        'update_available_message': 'Uma nova versão do Powerpointador está disponível.\n\nVersão atual: {version_actual}\nNova versão: {version_nueva}\n\nDeseja baixá-la?',
        'intentando_generar_imagen': 'Tentando gerar imagem novamente',
        'respuesta_completa_modelo': 'Resposta completa do modelo: {respuesta}',
        'respuesta_procesada': 'Resposta processada: {respuesta}',
        'error_generacion_respuesta': 'Erro na geração da resposta: {error}',
        'error_intento': 'Erro na tentativa {intento}: {error}',
        'respuesta_generada_exitosamente': 'Resposta gerada com sucesso',
        'respuesta_no_valida': 'A resposta não é um dicionário válido, tentando novamente...',
        'error_generacion_imagen': 'Erro na geração da imagem: {error}',
        'error_generacion_imagen_gemini': 'Erro na geração da imagem com Gemini: {error}',
        'texto_recibido_modelo': 'Texto recebido do modelo: {texto}',
        'imagen_no_generada': 'Nenhuma imagem foi gerada na resposta',
        'confirm_exit': 'Confirmar saída',
        'generation_in_progress': 'Há uma geração em andamento. Tem certeza de que deseja sair?',
        'cancel_generation': 'CANCELAR',
        'ocultar_log': 'Ocultar progresso',
        'mostrar_log': 'Mostrar progresso',
        'revisar_pdf': 'Revisar',
        'error_abrir_pdf': 'Erro ao abrir o documento: {error}',
        'aviso': 'Aviso',
        'ningun_documento': 'Nenhum documento carregado',
        'font_label': 'Fonte da letra:',
        'title_font_label': 'Fonte do título:',
        'content_font_label': 'Fonte do conteúdo:',
        'title_font_size_label': 'Tamanho do título:',
        'content_font_size_label': 'Tamanho do conteúdo:',
        'title_bold': 'Negrito',
        'title_italic': 'Itálico',
        'title_underline': 'Sublinhado',
        'content_bold': 'Negrito',
        'content_italic': 'Itálico',
        'content_underline': 'Sublinhado',
        'language_option_es': 'Espanhol',
        'language_option_en': 'Inglês',
        'language_option_fr': 'Francês',
        'language_option_pt': 'Português',
        'language_option_it': 'Italiano',
        'language_option_de': 'Alemão'
    },
    'it': {
        'auto_open': 'Apri presentazione automaticamente',
        'num_diapositivas': 'Numero di diapositive:',
        'descripcion_presentacion': 'Descrivi la tua presentazione:',
        'imagen_modelo': 'Modello IA Immagine:',
        'texto_modelo': 'Modello IA Testo:',
        'description_text': 'Configura una chiave API di Google, Replicate o xAI per usare il programma',
        'contador_label': '{} parole',
        'obtener_google_api': 'Ottieni chiave API Google',
        'configurar_google_api': 'Configura chiave API Google',
        'borrar_google_api': 'Elimina chiave API Google',
        'obtener_replicate_api': 'Ottieni chiave API Replicate',
        'configurar_replicate_api': 'Configura chiave API Replicate',
        'borrar_replicate_api': 'Elimina chiave API Replicate',
        'obtener_xai_api': 'Ottieni chiave API xAI',
        'configurar_xai_api': 'Configura chiave API xAI',
        'borrar_xai_api': 'Elimina chiave API xAI',
        'cargar_pdf': 'Carica documento',
        'pdf_cargado': 'Documento caricato: {}',
        'eliminar_pdf': 'Rimuovi',
        'error_cargar_pdf': 'Errore durante il caricamento del documento',
        'error_pdf_vacio': 'Il documento non contiene testo estraibile',
        'pdf_filter': 'Documenti (*.pdf *.txt)',
        'seleccionar_pdf': 'Seleziona documento',
        'google_api_config_window': 'Configurazione API Google',
        'google_api_key_prompt': 'Inserisci la tua chiave API Google:',
        'copy_api_clipboard': 'Copia API negli appunti',
        'valid_key': 'Chiave valida',
        'validate_save': 'Valida e salva',
        'empty_field_error': 'Il campo non può essere vuoto',
        'invalid_key': 'Chiave non valida',
        'timeout_error': 'Errore di connessione: Timeout',
        'connection_error': 'Errore di connessione: Impossibile connettersi al server',
        'generic_error': 'Errore di connessione: {}',
        'replicate_api_config_window': 'Configurazione API Replicate',
        'replicate_api_key_prompt': 'Inserisci la tua chiave API Replicate:',
        'xai_api_config_window': 'Configurazione API xAI',
        'xai_api_key_prompt': 'Inserisci la tua chiave API xAI:',
        'invalid_key_format': 'Formato chiave non valido. Deve iniziare con "xai-"',
        'balance_window_title': 'Saldo totale',
        'text_costs': 'Testo: ${:.5f}',
        'image_costs': 'Immagini: ${:.5f}',
        'total_costs': 'Totale: ${:.5f}',
        'check_xai_balance': 'Verifica su xAI',
        'check_replicate_balance': 'Verifica su Replicate',
        'reset_costs': 'Azzera costi',
        'confirm_reset_title': 'Conferma azzeramento',
        'confirm_reset_message': 'Sei sicuro di voler azzerare i costi?',
        'yes': 'Sì',
        'no': 'No',
        'accumulated_costs_title': 'Costi totali approssimativi accumulati',
        'google_delete_confirm_title': 'Conferma eliminazione API Google',
        'google_delete_confirm_message': 'Sei sicuro di voler eliminare la chiave API Google?',
        'google_invalid_api_title': 'API Google non valida',
        'google_invalid_api_message': 'La chiave API Google non è valida. Inserisci una nuova chiave API Google.',
        'google_connection_error_title': 'Errore di connessione Google',
        'google_connection_error_message': 'Impossibile validare la chiave API Google. Verifica la tua connessione internet.',
        'google_api_deleted_title': 'Chiave API eliminata',
        'google_api_deleted_message': 'La chiave API Google è stata eliminata correttamente.',
        'replicate_delete_confirm_title': 'Conferma eliminazione API Replicate',
        'replicate_delete_confirm_message': 'Sei sicuro di voler eliminare la chiave API Replicate?',
        'replicate_api_deleted_title': 'Chiave API eliminata',
        'replicate_api_deleted_message': 'La chiave API Replicate è stata eliminata correttamente.',
        'xai_delete_confirm_title': 'Conferma eliminazione API xAI',
        'xai_delete_confirm_message': 'Sei sicuro di voler eliminare la chiave API xAI?',
        'xai_api_deleted_title': 'Chiave API eliminata',
        'xai_api_deleted_message': 'La chiave API xAI è stata eliminata correttamente.',
        'language_instruction': 'italiano',
        'connection_error_title': 'Errore di connessione',
        'connection_error_message': 'Nessuna connessione Internet rilevata.\nPowerpointista necessita di una connessione Internet per funzionare.',
        'retry': 'Riprova',
        'exit': 'Esci',
        'too_many_words': 'La descrizione contiene troppe parole. Riduci il testo.',
        'too_few_words': 'La descrizione deve contenere almeno 10 parole.',
        'empty_description': 'Scrivi una descrizione per la tua presentazione.',
        'image_required': 'Devi caricare un\'immagine per usare questo modello di immagine.',
        'save_presentation': 'Salva presentazione',
        'default_filename': 'Presentazione_Powerpointista.pptx',
        'pptx_filter': 'Presentazioni (*.pptx)',
        'vista_previa_title': 'Anteprima diapositive',
        'vista_previa_empty_message': 'Le anteprime delle diapositive\nverranno mostrate qui\nman mano che vengono generate.',
        'generating_window_title': 'Generazione PowerPoint...',
        'app_title': 'Powerpointista',
        'generation_successful': 'Presentazione generata con successo!',
        'presentation_ready': 'Presentazione pronta',
        'presentation_generated_successfully': 'La tua presentazione "{nombre_archivo}" è stata generata correttamente in:\n{ruta_completa}',
        'generation_finish_error': 'Errore durante la finalizzazione della generazione: {error}',
        'generation_cancelled': 'Generazione annullata dall\'utente.',
        'confirm_cancellation': 'Conferma annullamento',
        'cancel_generation_confirm': 'Sei sicuro di voler annullare la generazione in corso?',
        'error': 'Errore',
        'generation_error': 'Errore durante la generazione della presentazione: {error}',
        'intentando_generar_respuesta': 'Tentativo di generare risposta con {modelo}...',
        'respuesta_modelo': 'Risposta dal modello {modelo}: {respuesta}',
        'tupla_generada': 'La tupla generata dal modello è stata: {respuesta}',
        'error_obtener_respuesta': 'Errore in obtener_respuesta_ia: {error}',
        'generando_texto': 'Generazione testo con il modello {modelo}...',
        'no_respuesta_modelo_texto': 'Impossibile ottenere risposta dal modello di testo',
        'generando_imagen': '\nGenerazione immagine {numero}/{total}',
        'imagen_generada_correctamente': 'Immagine {numero} generata correttamente',
        'error_generando_imagen': 'Errore generazione immagine {numero}: {error}',
        'aplicando_disenos': '\nApplicazione design alle diapositive...',
        'diapositiva_completada': 'Diapositiva {numero}/{total} completata',
        'error_aplicando_diseno': 'Errore applicazione design alla diapositiva {numero}: {error}',
        'error_generacion_presentacion': 'Errore durante la generazione della presentazione: {error}',
        'error_generar_imagen': 'Errore durante la generazione dell\'immagine: {error}',
        'error_imagen_requerida': 'È richiesta un\'immagine personalizzata valida per questo modello',
        'slide_previous': 'Precedente',
        'slide_next': 'Successiva',
        'update_available_title': 'Aggiornamento disponibile',
        'update_available_message': 'È disponibile una nuova versione di Powerpointista.\n\nVersione attuale: {version_actual}\nNuova versione: {version_nueva}\n\nVuoi scaricarla?',
        'intentando_generar_imagen': 'Nuovo tentativo generazione immagine',
        'respuesta_completa_modelo': 'Risposta completa del modello: {respuesta}',
        'respuesta_procesada': 'Risposta elaborata: {respuesta}',
        'error_generacion_respuesta': 'Errore nella generazione della risposta: {error}',
        'error_intento': 'Errore nel tentativo {intento}: {error}',
        'respuesta_generada_exitosamente': 'Risposta generata con successo',
        'respuesta_no_valida': 'La risposta non è un dizionario valido, nuovo tentativo...',
        'error_generacion_imagen': 'Errore nella generazione dell\'immagine: {error}',
        'error_generacion_imagen_gemini': 'Errore nella generazione dell\'immagine con Gemini: {error}',
        'texto_recibido_modelo': 'Testo ricevuto dal modello: {texto}',
        'imagen_no_generada': 'Nessuna immagine generata nella risposta',
        'confirm_exit': 'Conferma uscita',
        'generation_in_progress': 'Generazione in corso. Sei sicuro di voler uscire?',
        'cancel_generation': 'ANNULLA',
        'ocultar_log': 'Nascondi progressi',
        'mostrar_log': 'Mostra progressi',
        'revisar_pdf': 'Rivedi',
        'error_abrir_pdf': 'Errore apertura documento: {error}',
        'aviso': 'Avviso',
        'ningun_documento': 'Nessun documento caricato',
        'font_label': 'Carattere:',
        'title_font_label': 'Carattere titolo:',
        'content_font_label': 'Carattere contenuto:',
        'title_font_size_label': 'Dimensione titolo:',
        'content_font_size_label': 'Dimensione contenuto:',
        'title_bold': 'Grassetto',
        'title_italic': 'Corsivo',
        'title_underline': 'Sottolineato',
        'content_bold': 'Grassetto',
        'content_italic': 'Corsivo',
        'content_underline': 'Sottolineato',
        'language_option_es': 'Spagnolo',
        'language_option_en': 'Inglese',
        'language_option_fr': 'Francese',
        'language_option_pt': 'Portoghese',
        'language_option_it': 'Italiano',
        'language_option_de': 'Tedesco'
    },
    'de': {
        'auto_open': 'Präsentation automatisch öffnen',
        'num_diapositivas': 'Anzahl der Folien:',
        'descripcion_presentacion': 'Beschreiben Sie Ihre Präsentation:',
        'imagen_modelo': 'KI-Bildmodell:',
        'texto_modelo': 'KI-Textmodell:',
        'description_text': 'Konfigurieren Sie einen Google-, Replicate- oder xAI-API-Schlüssel, um das Programm zu verwenden',
        'contador_label': '{} Wörter',
        'obtener_google_api': 'Google API-Schlüssel erhalten',
        'configurar_google_api': 'Google API-Schlüssel konfigurieren',
        'borrar_google_api': 'Google API-Schlüssel löschen',
        'obtener_replicate_api': 'Replicate API-Schlüssel erhalten',
        'configurar_replicate_api': 'Replicate API-Schlüssel konfigurieren',
        'borrar_replicate_api': 'Replicate API-Schlüssel löschen',
        'obtener_xai_api': 'xAI API-Schlüssel erhalten',
        'configurar_xai_api': 'xAI API-Schlüssel konfigurieren',
        'borrar_xai_api': 'xAI API-Schlüssel löschen',
        'cargar_pdf': 'Dokument laden',
        'pdf_cargado': 'Dokument geladen: {}',
        'eliminar_pdf': 'Entfernen',
        'error_cargar_pdf': 'Fehler beim Laden des Dokuments',
        'error_pdf_vacio': 'Das Dokument enthält keinen extrahierbaren Text',
        'pdf_filter': 'Dokumente (*.pdf *.txt)',
        'seleccionar_pdf': 'Dokument auswählen',
        'google_api_config_window': 'Google API-Konfiguration',
        'google_api_key_prompt': 'Geben Sie Ihren Google API-Schlüssel ein:',
        'copy_api_clipboard': 'API in Zwischenablage kopieren',
        'valid_key': 'Gültiger Schlüssel',
        'validate_save': 'Validieren und speichern',
        'empty_field_error': 'Feld darf nicht leer sein',
        'invalid_key': 'Ungültiger Schlüssel',
        'timeout_error': 'Verbindungsfehler: Zeitüberschreitung',
        'connection_error': 'Verbindungsfehler: Konnte keine Verbindung zum Server herstellen',
        'generic_error': 'Verbindungsfehler: {}',
        'replicate_api_config_window': 'Replicate API-Konfiguration',
        'replicate_api_key_prompt': 'Geben Sie Ihren Replicate API-Schlüssel ein:',
        'xai_api_config_window': 'xAI API-Konfiguration',
        'xai_api_key_prompt': 'Geben Sie Ihren xAI API-Schlüssel ein:',
        'invalid_key_format': 'Ungültiges Schlüsselformat. Muss mit "xai-" beginnen',
        'balance_window_title': 'Gesamtsaldo',
        'text_costs': 'Text: ${:.5f}',
        'image_costs': 'Bilder: ${:.5f}',
        'total_costs': 'Gesamt: ${:.5f}',
        'check_xai_balance': 'Auf xAI prüfen',
        'check_replicate_balance': 'Auf Replicate prüfen',
        'reset_costs': 'Kosten zurücksetzen',
        'confirm_reset_title': 'Zurücksetzen bestätigen',
        'confirm_reset_message': 'Sind Sie sicher, dass Sie die Kosten auf Null zurücksetzen möchten?',
        'yes': 'Ja',
        'no': 'Nein',
        'accumulated_costs_title': 'Gesamte angesammelte ungefähre Kosten',
        'google_delete_confirm_title': 'Löschen der Google API bestätigen',
        'google_delete_confirm_message': 'Sind Sie sicher, dass Sie den Google API-Schlüssel löschen möchten?',
        'google_invalid_api_title': 'Ungültige Google API',
        'google_invalid_api_message': 'Der Google API-Schlüssel ist ungültig. Geben Sie einen neuen Google API-Schlüssel ein.',
        'google_connection_error_title': 'Google Verbindungsfehler',
        'google_connection_error_message': 'Der Google API-Schlüssel konnte nicht validiert werden. Überprüfen Sie Ihre Internetverbindung.',
        'google_api_deleted_title': 'API-Schlüssel gelöscht',
        'google_api_deleted_message': 'Der Google API-Schlüssel wurde erfolgreich gelöscht.',
        'replicate_delete_confirm_title': 'Löschen der Replicate API bestätigen',
        'replicate_delete_confirm_message': 'Sind Sie sicher, dass Sie den Replicate API-Schlüssel löschen möchten?',
        'replicate_api_deleted_title': 'API-Schlüssel gelöscht',
        'replicate_api_deleted_message': 'Der Replicate API-Schlüssel wurde erfolgreich gelöscht.',
        'xai_delete_confirm_title': 'Löschen der xAI API bestätigen',
        'xai_delete_confirm_message': 'Sind Sie sicher, dass Sie den xAI API-Schlüssel löschen möchten?',
        'xai_api_deleted_title': 'API-Schlüssel gelöscht',
        'xai_api_deleted_message': 'Der xAI API-Schlüssel wurde erfolgreich gelöscht.',
        'language_instruction': 'deutsch',
        'connection_error_title': 'Verbindungsfehler',
        'connection_error_message': 'Keine Internetverbindung erkannt.\nPowerPointkünstler benötigt eine Internetverbindung, um zu funktionieren.',
        'retry': 'Wiederholen',
        'exit': 'Beenden',
        'too_many_words': 'Die Beschreibung enthält zu viele Wörter. Bitte kürzen Sie den Text.',
        'too_few_words': 'Die Beschreibung muss mindestens 10 Wörter enthalten.',
        'empty_description': 'Bitte schreiben Sie eine Beschreibung für Ihre Präsentation.',
        'image_required': 'Sie müssen ein Bild hochladen, um dieses Bildmodell zu verwenden.',
        'save_presentation': 'Präsentation speichern',
        'default_filename': 'PowerPointkünstler_Präsentation.pptx',
        'pptx_filter': 'Präsentationen (*.pptx)',
        'vista_previa_title': 'Folienvorschau',
        'vista_previa_empty_message': 'Die Vorschauen der Folien\nwerden hier angezeigt,\nsobald sie generiert werden.',
        'generating_window_title': 'PowerPoint wird generiert...',
        'app_title': 'PowerPointkünstler',
        'generation_successful': 'Präsentation erfolgreich generiert!',
        'presentation_ready': 'Präsentation bereit',
        'presentation_generated_successfully': 'Ihre Präsentation "{nombre_archivo}" wurde erfolgreich generiert in:\n{ruta_completa}',
        'generation_finish_error': 'Fehler beim Abschließen der Generierung: {error}',
        'generation_cancelled': 'Generierung vom Benutzer abgebrochen.',
        'confirm_cancellation': 'Abbruch bestätigen',
        'cancel_generation_confirm': 'Sind Sie sicher, dass Sie die aktuelle Generierung abbrechen möchten?',
        'error': 'Fehler',
        'generation_error': 'Fehler beim Generieren der Präsentation: {error}',
        'intentando_generar_respuesta': 'Versuche, Antwort mit {modelo} zu generieren...',
        'respuesta_modelo': 'Antwort vom Modell {modelo}: {respuesta}',
        'tupla_generada': 'Das vom Modell generierte Tupel war: {respuesta}',
        'error_obtener_respuesta': 'Fehler in obtener_respuesta_ia: {error}',
        'generando_texto': 'Generiere Text mit Modell {modelo}...',
        'no_respuesta_modelo_texto': 'Konnte keine Antwort vom Textmodell erhalten',
        'generando_imagen': '\nGeneriere Bild {numero}/{total}',
        'imagen_generada_correctamente': 'Bild {numero} erfolgreich generiert',
        'error_generando_imagen': 'Fehler beim Generieren von Bild {numero}: {error}',
        'aplicando_disenos': '\nWende Designs auf Folien an...',
        'diapositiva_completada': 'Folie {numero}/{total} abgeschlossen',
        'error_aplicando_diseno': 'Fehler beim Anwenden des Designs auf Folie {numero}: {error}',
        'error_generacion_presentacion': 'Fehler während der Präsentationsgenerierung: {error}',
        'error_generar_imagen': 'Fehler beim Generieren des Bildes: {error}',
        'error_imagen_requerida': 'Für dieses Modell ist ein gültiges benutzerdefiniertes Bild erforderlich',
        'slide_previous': 'Zurück',
        'slide_next': 'Weiter',
        'update_available_title': 'Update verfügbar',
        'update_available_message': 'Eine neue Version von PowerPointkünstler ist verfügbar.\n\nAktuelle Version: {version_actual}\nNeue Version: {version_nueva}\n\nMöchten Sie sie herunterladen?',
        'intentando_generar_imagen': 'Versuche Bildgenerierung erneut',
        'respuesta_completa_modelo': 'Vollständige Modellantwort: {respuesta}',
        'respuesta_procesada': 'Verarbeitete Antwort: {respuesta}',
        'error_generacion_respuesta': 'Fehler bei der Antwortgenerierung: {error}',
        'error_intento': 'Fehler bei Versuch {intento}: {error}',
        'respuesta_generada_exitosamente': 'Antwort erfolgreich generiert',
        'respuesta_no_valida': 'Die Antwort ist kein gültiges Wörterbuch, versuche es erneut...',
        'error_generacion_imagen': 'Fehler bei der Bildgenerierung: {error}',
        'error_generacion_imagen_gemini': 'Fehler bei der Bildgenerierung mit Gemini: {error}',
        'texto_recibido_modelo': 'Vom Modell empfangener Text: {texto}',
        'imagen_no_generada': 'In der Antwort wurde kein Bild generiert',
        'confirm_exit': 'Beenden bestätigen',
        'generation_in_progress': 'Eine Generierung läuft gerade. Sind Sie sicher, dass Sie beenden möchten?',
        'cancel_generation': 'ABBRECHEN',
        'ocultar_log': 'Fortschritt ausblenden',
        'mostrar_log': 'Fortschritt anzeigen',
        'revisar_pdf': 'Überprüfen',
        'error_abrir_pdf': 'Fehler beim Öffnen des Dokuments: {error}',
        'aviso': 'Hinweis',
        'ningun_documento': 'Kein Dokument geladen',
        'font_label': 'Schriftart:',
        'title_font_label': 'Titelschriftart:',
        'content_font_label': 'Inhaltsschriftart:',
        'title_font_size_label': 'Titelgröße:',
        'content_font_size_label': 'Inhaltsgröße:',
        'title_bold': 'Fett',
        'title_italic': 'Kursiv',
        'title_underline': 'Unterstrichen',
        'content_bold': 'Fett',
        'content_italic': 'Kursiv',
        'content_underline': 'Unterstrichen',
        'language_option_es': 'Spanisch',
        'language_option_en': 'Englisch',
        'language_option_fr': 'Französisch',
        'language_option_pt': 'Portugiesisch',
        'language_option_it': 'Italienisch',
        'language_option_de': 'Deutsch'
    }
}

def obtener_traduccion(clave, idioma='es'):
    # >>> Añadir 'fr' a la lista de idiomas válidos <<<
    if idioma not in traducciones:
        idioma = 'es' # Volver a español si el idioma no es válido

    lang_dict = traducciones.get(idioma, traducciones.get('es', {}))
    translation = lang_dict.get(clave)

    if translation is None:
        # Si no se encuentra en el idioma actual, buscar en español como fallback
        es_dict = traducciones.get('es', {})
        translation = es_dict.get(clave, clave) # Devolver la clave si no se encuentra en español

    return translation